language: c
sudo: false

addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake

os:
  - linux
  # - osx

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.4)
    # - LUA=luajit2.0  # current head of 2.0 branch
    # - LUA=luajit2.1  # current head of 2.1 branch

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install luv
  - luarocks install luabitop
  - luarocks install --server=http://luarocks.org/dev luaffi
  - curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh
  - ./lit install creationix/pretty-print

script:
  - lua test.lua

notifications:
  email:
    on_success: change
    on_failure: always
