language: c
sudo: false

os:
  - linux
  # - osx

env:
  matrix:
    - LUA=luvit-2
    - LUA=luajit-2.0
    - LUA=luajit-2.1
    - LUA=lua-5.1
    - LUA=lua-5.2
    # - LUA=lua-5.3 # There is no bitop library for lua5.3

before_install:
  - source .travis/setenv.sh
  - lit install luvit/pretty-print

script:
  - lua test.lua

notifications:
  email:
    on_success: change
    on_failure: always
