language: c
sudo: false


os:
  - linux
  # - osx

env:
  matrix:
    - LUA='luajit/2.0.4'
    - LUA='lua/5.1.5'
    - LUA='lua/5.2.4'
    - LUA='lua/5.3.2'

before_install:
  - cd .travis; source setenv.sh
  - lit install luvit/pretty-print

script:
  - lua test.lua

notifications:
  email:
    on_success: change
    on_failure: always
